# Custom Plugins Configuration

- slug: advanced-custom-fields
  system: github
  owner: AdvancedCustomFields
  repo: acf
  frequency: 60 # Update frequency in minutes

- slug: morpheus-plugin
  system: github
  owner: blogvault
  repo: morpheus-plugin
  frequency: 60 # Update frequency in minutes

- slug: gravity-pdf
  system: github
  owner: GravityPDF
  repo: gravity-pdf
  frequency: 60 # Update frequency in minutes
